name: Pipeline to deploy infrastructure and application code to AWS

on:
  push:
    branches:
      - "master"
      - "staging"
      - "develop"

env:
  TEMPLATE: template.yml

  # Pro Env variables
  PROD_APP_NAME: blossom-deployment-test
  PROD_APP_ENV: prod
  PROD_PIPELINE_EXECUTION_ROLE: arn:aws:iam::782046926924:role/GithubActionsRole # TODO: send to github actions secrets
  STACK_TEMPLATES_BUCKET: stacks-templates-a758baa3
  PROD_REGION: us-east-1
  DB_USER_NAME: myusername # TODO: send to github actions secrets

defaults:
  run:
    working-directory: ./infrastructure

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  # Production Pipelines
  deploy-prod:
    name: Build and deploy Cloudformation resources to production environment
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.PROD_PIPELINE_EXECUTION_ROLE }} #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.PROD_REGION }}

      - name: Check files in working directory
        run: ls -al

      - name: Upload CloudFormation template to S3 bucket
        run: |
          aws s3 sync . s3://${{ env.STACK_TEMPLATES_BUCKET }} --region ${{ env.PROD_REGION }}

      - name: Deploy cloudformation Stacks
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: oiss-infra-dev
          template: ./infrastructure/${{ env.TEMPLATE }}
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: >-
            AppName=${{ env.PROD_APP_NAME }}
            AppEnv=${{ env.PROD_APP_ENV }}
            DBUser=${{ env.DB_USER_NAME }}
